"""add_kyc_status_to_users

Revision ID: 40ab1ee913c6
Revises: 1080b6b02700
Create Date: 2025-12-26 11:13:09.539899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ab1ee913c6'
down_revision: Union[str, None] = '1080b6b02700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_status', sa.Enum('NONE', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus', create_type=False), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_status')
    # ### end Alembic commands ###
