"""Add Consumer Subscriptions

Revision ID: 4899f961e8d5
Revises: 9093626c23d6
Create Date: 2025-12-24 12:15:21.240718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4899f961e8d5'
down_revision: Union[str, None] = '9093626c23d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='consumersubscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('monthly_price', sa.Float(), nullable=False, server_default='9.99'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_price')
    op.drop_table('consumer_subscriptions')
    # ### end Alembic commands ###
