"""Initial Schema

Revision ID: 6f52a8591bcd
Revises: 
Create Date: 2025-12-24 11:30:56.382629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f52a8591bcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('role', sa.Enum('ADMIN', 'CREATOR', 'CONSUMER', name='userrole'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),

        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'CREATOR', 'CONSUMER', name='userrole'),
               type_=postgresql.ENUM('user', 'merchant', 'auditor', 'admin', name='userroleenum'),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('users', 'kyc_status')
    op.drop_column('users', 'hashed_password')
    op.create_table('audit_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='audit_logs_payment_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_table('fx_rates_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('base_asset', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quote_asset', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fx_rates_history_pkey')
    )
    op.create_index('ix_fx_rates_history_id', 'fx_rates_history', ['id'], unique=False)
    op.create_index('ix_fx_rates_history_fetched_at', 'fx_rates_history', ['fetched_at'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('wallets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_wallets_id', 'wallets', ['id'], unique=False)
    op.create_index('ix_wallets_address', 'wallets', ['address'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('merchant_wallet_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('merchant_wallet_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payer_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payer_wallet_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount_usdt', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('amount_clp_reference', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('fx_rate_usdt_clp', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'expired', 'cancelled', name='paymentstatusenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tx_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_from_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_to_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_amount_usdt', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('tx_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_status_change_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['merchant_user_id'], ['users.id'], name='payments_merchant_user_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_wallet_id'], ['wallets.id'], name='payments_merchant_wallet_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], name='payments_payer_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('tx_hash', name='payments_tx_hash_key')
    )
    op.create_index('ix_payments_public_id', 'payments', ['public_id'], unique=True)
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    # ### end Alembic commands ###
