"""add_auditlog_timestamp

Revision ID: 8a2a45559f11
Revises: 81625f70f9c1
Create Date: 2025-12-27 23:03:07.145961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2a45559f11'
down_revision: Union[str, None] = '81625f70f9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'created_at')
    # ### end Alembic commands ###
