"""add_creator_subscription_fields

Revision ID: 98273a0204bd
Revises: 8a2a45559f11
Create Date: 2025-12-28 00:50:53.376157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98273a0204bd'
down_revision: Union[str, None] = '8a2a45559f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_enabled')
    # ### end Alembic commands ###
