"""Add tags category cover_image_url

Revision ID: a7f661e534ee
Revises: 40ab1ee913c6
Create Date: 2025-12-26 18:49:47.515990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7f661e534ee'
down_revision: Union[str, None] = '40ab1ee913c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_content', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('cms_content', sa.Column('category', sa.String(), nullable=True))
    op.add_column('cms_content', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_content', 'cover_image_url')
    op.drop_column('cms_content', 'category')
    op.drop_column('cms_content', 'tags')
    # ### end Alembic commands ###
