"""Update Subscription Status Enum

Revision ID: d692f8474b4d
Revises: bea171f0331e
Create Date: 2025-12-24 12:31:04.917812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd692f8474b4d'
down_revision: Union[str, None] = 'bea171f0331e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_subscriptions', sa.Column('proof_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumer_subscriptions', 'proof_tx_hash')
    # ### end Alembic commands ###
