"""add_media_is_public_preview

Revision ID: da4bc1da1151
Revises: d0a19f7b7f24
Create Date: 2026-01-07 11:34:45.915057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4bc1da1151'
down_revision: Union[str, None] = 'd0a19f7b7f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_media', sa.Column('is_public_preview', sa.Boolean(), nullable=True))
    op.execute("UPDATE cms_media SET is_public_preview = false")
    op.alter_column('cms_media', 'is_public_preview', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_media', 'is_public_preview')
    # ### end Alembic commands ###
